// This file is auto-generated by @hey-api/openapi-ts

export const HealthResponseSchema = {
  type: 'object',
  required: ['status'],
  properties: {
    status: {
      type: 'string',
      enum: ['ok'],
    },
  },
} as const;
