// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

export type HealthResponse = {
  status: 'ok';
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type GetHealthResponses = {
  /**
   * Service is healthy
   */
  200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
