// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zHealthResponse = z.object({
  status: z.enum(['ok']),
});

/**
 * Service is healthy
 */
export const zGetHealthResponse = zHealthResponse;
